changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: Improvements
      labels:
        - improvement
        - refactor
        - performance
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
